### PR TITLE
Backtraces, diagnostics improvements, MLIR/LLVM updates

### LINKED ISSUE #497: Flaky test failure erlang::cancel_timer_1::with_local_reference::with_timer::with_timeout_returns_false_after_timeout_message_was_sent
Sometimes, but not always this test causes an assertion failure:

## Reproduction Steps

```
cargo test --package liblumen_otp erlang::cancel_timer_1::with_local_reference::with_timer::with_timeout_returns_false_after_timeout_message_was_sent`
```

## Output

```
---
thread 'erlang::cancel_timer_1::with_local_reference::with_timer::with_timeout_returns_false_after_timeout_message_was_sent' panicked at 'stdout = 
stderr =    Compiling tests/lib/erlang/cancel_timer_1/with_local_reference/with_timer/with_timeout_returns_false_after_timeout_message_was_sent/init.erl
Assertion failed: (BitWidth == RHS.BitWidth && "Comparison requires equal bit widths"), function operator==, file /Users/runner/.local/share/llvm/lumen/include/llvm/ADT/APInt.h, line 1153.
', native_implemented/otp/tests/./test.rs:61:5
```

Seen in https://github.com/lumen/lumen/pull/496/checks?check_run_id=976358466, but not https://github.com/lumen/lumen/runs/976240956 and I can only sometimes reproduce it locally also.

### LINKED ISSUE #559: Any call to `exit` results in failed assertion in the codegen
With https://github.com/lumen/lumen/pull/551 (simply updates eir, some changes to the IR produced by passes), any module which calls `exit` results in a failed assertion in the compiler.

```
-module(init).
-export([start/0]).

start() ->
    exit(abnormal).
```

```
lumen: /lumen/compiler/codegen_llvm/lib/lumen/EIR/Builder/ModuleBuilder.cpp:1153: bool lumen::eir::ModuleBuilder::maybe_build_intrinsic(mlir::Location, llvm::StringRef, ArrayRef<mlir::Value>, bool, mlir::Block *, ArrayRef<mlir::Value>): Assertion `resultOpt.hasValue()' failed.
```

The eir seems to be valid to me, it's very simple:
```
start/0 {
  block22(%57, %58):
    %28 = a'erlang':a'exit'/1;
    %28(a'abnormal') => %57 except %58;
}
```

### PR DESCRIPTION
**Pull request by bitwalker**
Fixes #559
Fixes #497

- [x] **NOTE:** I need to push a new release of MLIR/LLVM before this will build.

Of primary interest here is the changes to how exceptions are handled, as it directly ties in to backtraces and the interaction with exceptions in the generated code. Ultimately the goal is to have them unified, so that from the runtime perspective, exceptions thrown from the generated code appear as a `RuntimeException` with an associated `Trace` object which can then be serialized as a term, pretty printed, and passed around including beyond the scope of the originating process. Likewise, if the runtime wants to raise an exception from a BIF, it may do so with a `RuntimeException` and `process_raise`, and have it interact natively with the exception handling in the generated code.

There are a lot of legacy bits in liblumen_alloc that probably need to be removed as we gain infra in the generated code. In particular, the legacy Frame stuff that exists to support existing test infrastructure/the interpreter. Of secondary note is the `source` value associated with `RuntimeException` values, as those should be almost universally superceded by `Trace`, and if not, we probably need good justification for keeping such errors as `RuntimeException` values, since it is not possible to reify an Erlang stacktrace from them, which is critical for any errors that can be caught from generated code.

### CODE REVIEW

**Comment by KronicDeth** [comment]
@bitwalker do you want to resolve the merge conflict, or do you want me to resolve the merge conflict?  Also, per your ask of using rebase only when there isn't merge conflict, if I do fix the merge conflicts, do you want me to rebase and force push or to have merge commit?  I can also leave the merge commit on the PR branch, but then we can still use GitHub's Rebase and Merge if you want to eliminate it before the PR merge.

File: liblumen_alloc/src/erts/module_function_arity.rs [hunk 1]
```diff
@@ -10,12 +12,46 @@ pub struct ModuleFunctionArity {
...
     pub arity: Arity,
 }
+impl ModuleFunctionArity {
+    #[inline]
+    pub fn from_symbol_name(s: impl AsRef<str>) -> Result<Self, ()> {
+        s.as_ref().parse::<Self>()
+    }
+}
+
+impl FromStr for ModuleFunctionArity {
```
Comment (KronicDeth) [inline liblumen_alloc/src/erts/module_function_arity.rs:22]: Neat

File: liblumen_alloc/src/erts/module_function_arity.rs [hunk 2]
```diff
@@ -10,12 +12,46 @@ pub struct ModuleFunctionArity {
...
+        }
+    }
+}
 
 impl Display for ModuleFunctionArity {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
         write!(
             f,
-            "fun {}:{}/{}",
+            "{}:{}/{}",
```
Comment (KronicDeth) [inline liblumen_alloc/src/erts/module_function_arity.rs:54]: ❤️  This was on my TODO list for a long time that it just didn't look right with `fun` anymore for all its usages.

File: liblumen_alloc/src/erts/process/trace/backtrace.rs [hunk 3]
```diff
@@ -0,0 +1,338 @@
...
+    }
+}
+
+impl Iterator for SymbolIter<'_> {
+    type Item = Symbolication;
+
+    fn next(&mut self) -> Option<Self::Item> {
+        use std::convert::TryInto;
+
+        println!("{:?}", &self.pos);
```
Comment (KronicDeth) [inline liblumen_alloc/src/erts/process/trace/backtrace.rs:163]: These two `println!` look like they are for debug purposes.  Should they be removed?

File: liblumen_alloc/src/erts/process/trace/format.rs [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+fn trim_filename(file: &Path) -> Cow<'_, str> {
+    let filename = file.to_string_lossy();
+    if filename.starts_with("/rustc/") {
+        if let Some(filename) = filename.get(48..) {
+            Cow::Owned(format!("rust:{}", filename))
+        } else {
+            filename
+        }
+    } else if let Some(basename) = file.file_name().and_then(|x| x.to_str()) {
+        if basename.starts_with('<') && basename.ends_with('>') {
```
Comment (KronicDeth) [inline liblumen_alloc/src/erts/process/trace/format.rs:145]: What's the significance of `<FILENAME>`?

File: liblumen_alloc/src/erts/process/trace/utils.rs [hunk 5]
```diff
@@ -0,0 +1,264 @@
...
+            Err(())
+        }
+    }
+}
+
+// Minimum frame size is a 4 element tuple with all immediates (i.e. nil for the location info)
+pub const MIN_FRAME_SIZE: usize = 5 * mem::size_of::<Term>();
+// Base frame size is a 4 element tuple, 2 cons cells, and 2 2-element tuples,
+// and 1 character list of up to 120 chars of which each char requires a cons cell
+pub const MAX_FILENAME_LEN: usize = 120;
```
Comment (KronicDeth) [inline liblumen_alloc/src/erts/process/trace/utils.rs:149]: Why a max of 120 characters?  We know Window's 256 character path limit causes problems, so why 120 here?

File: compiler/codegen_llvm/lib/lumen/EIR/Builder/ModuleBuilder.cpp [hunk 6]
```diff
@@ -213,12 +218,6 @@ extern "C" MLIRModuleRef MLIRFinalizeModuleBuilder(MLIRModuleBuilderRef b) {
   ModuleBuilder *builder = unwrap(b);
   auto finished = builder->finish();
   delete builder;
-  if (failed(mlir::verify(finished))) {
```
[the remark this answers is not in the document]
Comment (bitwalker) [reply compiler/codegen_llvm/lib/lumen/EIR/Builder/ModuleBuilder.cpp:216]: It's handled elsewhere now, but verification still happens of course

File: compiler/codegen_llvm/lib/lumen/EIR/Builder/ModuleBuilder.cpp [hunk 7]
```diff
@@ -1119,7 +1133,8 @@ bool ModuleBuilder::maybe_build_intrinsic(Location loc, StringRef target,
                      .Case("erlang:raise/3", true)
                      .Default(false);
 
-  assert(resultOpt.hasValue());
+  if (isThrow) return true;
```
[the remark this answers is not in the document]
Comment (bitwalker) [reply compiler/codegen_llvm/lib/lumen/EIR/Builder/ModuleBuilder.cpp:1136]: Yep, just skips lowering the call prologue stuff (i.e. returns/branches) if the call was an error intrinsic.

File: compiler/codegen_llvm/lib/lumen/EIR/Conversion/MathOpConversions.cpp [hunk 8]
```diff
@@ -15,7 +15,7 @@ static Value specializeIntegerMathOp(Location loc,
 template <typename Op, typename T>
 static Value specializeFloatMathOp(Location loc, RewritePatternContext<Op> &ctx,
                                    Value lhs, Value rhs) {
-  auto fpTy = LLVMType::getDoubleTy(ctx.dialect);
```
[the remark this answers is not in the document]
Comment (bitwalker) [reply compiler/codegen_llvm/lib/lumen/EIR/Conversion/MathOpConversions.cpp:18]: Upstream change in MLIR, it used to be that the LLVMDialect needed to be passed around to access LLVM types, but that is no longer the case, the types are now part of the MLIR type system proper

File: compiler/llvm/src/diagnostics.rs [hunk 9]
```diff
@@ -96,82 +135,153 @@ impl OptimizationDiagnosticKind {
...
         Self {
             kind,
-            pass_name: pass_name.expect("got a non-UTF8 pass name from LLVM"),
+            pass_name,
+            remark_name,
             function,
-            line,
-            column,
-            filename,
-            message: message.expect("got a non-UTF8 OptimizationDiagnostic message from LLVM"),
```
[the remark this answers is not in the document]
Comment (bitwalker) [reply compiler/llvm/src/diagnostics.rs:151]: I just realized I can clean this up a bit more due to some other refactoring I did here, updated

File: liblumen_alloc/src/erts/process/trace/format.rs (hunk 4 above)
Comment (bitwalker) [reply liblumen_alloc/src/erts/process/trace/format.rs:145]: That's the format we give virtual files, e.g. `<nofile>`

File: liblumen_alloc/src/erts/process/trace/utils.rs (hunk 5 above)
Comment (bitwalker) [reply liblumen_alloc/src/erts/process/trace/utils.rs:149]: The trace code trims the paths down to this limit (leaving the tail of the path intact), so we're not discarding useful information, just excess path information that probably shouldn't be there anyway (i.e. absolute paths). The real reason is to avoid allocating enormous amounts of memory for a backtrace just due to long paths being present in the debug info. If paths were stored as binary terms and not lists, this wouldn't be worth the effort, but cons cells are so wasteful in terms of memory that placing a hard limit on them is well worth it for both performance and memory savings.

Comment (bitwalker) [reply liblumen_alloc/src/erts/process/trace/utils.rs:149]: Honestly every time I think about traces using lists for paths it makes me mad, I wonder if that detail is depended on in enough places to prevent getting that changed in OTP

Comment (KronicDeth) [reply liblumen_alloc/src/erts/process/trace/utils.rs:149]: Eh, leaving the tail is probably good enough.  It's still better than lldb only showing the basename by default.

**Comment by KronicDeth** [comment]
You might need to repackage the LLVM release @bitwalker.  

https://github.com/lumen/lumen/pull/554/checks?check_run_id=1034658062#step:7:427

says 

> error: could not find native static library `MLIREDSCInterface`

but I can't find it in the macOS release:

```
~/.local/share/llvm/clang+llvm-12.0.0-x86_64-apple-darwin19.5.0 
╰─$ ls **/*MLIRE*
lib/libMLIREDSC.a  lib/libMLIRExecutionEngine.a
```

**Comment by bitwalker** [comment]
@KronicDeth I think we should just merge this branch now, but not sure what this error is all about:

```
driver status: signal: 9
driver stdout:
    Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 49385
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Error: non-200 response code: 404
```

**Comment by KronicDeth** [comment]
@bitwalker that's the chrome driver being incompatible with chrome.  The macOS build boxes have the evergreen chrome, but I haven't found a way to keep the chromedriver compatible with it automatically, so I need to update it from time to time, but yeah, it should count as blocking for this.
